[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn -DskipTests clean package"]

[start]
cmd = "java -Djava.security.egd=file:/dev/./urandom -jar target/backend-0.0.1-SNAPSHOT.jar --server.port=$PORT"
